Tests
TatyanaKoryukalova/yanadachy228 pull request #6
Opened 2021-11-21 16:11 UTC by TatyanaKoryukalova

2021-12-04 22:40 UTC, GregoryKhakov reviewed
Есть вопрос по наименованию, в остальном все ок.

2021-12-04 22:40 UTC, GregoryKhakov commented on src/test/java/com/gmail/san666/yoshi/oop/CompanyTest.java
>      void firePerson() {
Суффикс Test не нужен?

2021-12-05 19:25 UTC, FedorZholud requested changes

2021-12-05 19:25 UTC, FedorZholud commented on src/test/java/com/gmail/san666/yoshi/oop/PersonTest.java
> +        Throwable thrown = catchThrowable(() -> alex.salaryValidate());
Так можно делать, но это усложнение, которое не нужно, поэтому нужно брать метод assertThatExceptionOfType

2021-12-05 19:25 UTC, FedorZholud commented on src/test/java/com/gmail/san666/yoshi/oop/CompanyTest.java
>      void firePerson() {
Как уже Гриша заметил нейминг нужно везде исправить, в данном случае будет shouldFirePerson.

2021-12-05 19:25 UTC, FedorZholud commented on src/test/java/com/gmail/san666/yoshi/oop/PersonTest.java
>  class PersonTest {
Тест для персоны не нужен, можешь его удалить, проверку на выкидывание эксепшена нужно будет сделать в тесте для метода hirePerson

2021-12-05 19:25 UTC, FedorZholud commented on src/test/java/com/gmail/san666/yoshi/oop/CompanyTest.java
>  class CompanyTest {
Нужно добавить тест shouldThrow...ExceptionWhenHirePerson  в котором ты будешь ловить ошибку валидации. К прошлому тикету я тебе добавил комментарий, что нужно добавить валидацию в метод hirePerson

2022-01-26 18:14 UTC, FedorZholud approved these changes

2022-01-28 06:41 UTC, merged